name: Windows Tailscale Setup & RDP

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Скачиваем установщик Tailscale
        shell: powershell
        run: |
          Write-Output "Скачиваем tailscale-setup.exe..."
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "$env:TEMP\tailscale-setup.exe"

      - name: Устанавливаем Tailscale
        shell: powershell
        run: |
          Write-Output "Устанавливаем Tailscale в тихом режиме..."
          # Параметр /S – тихая установка; убедитесь, что он поддерживается вашей версией установщика
          Start-Process -FilePath "$env:TEMP\tailscale-setup.exe" -ArgumentList "/S" -Wait

      - name: Запускаем Tailscale с authkey
        shell: powershell
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          Write-Output "Поднимаем Tailscale VPN..."
          # Путь может отличаться в зависимости от версии или настроек установки
          $tailscaleExe = "C:\Program Files\Tailscale IPN\tailscale.exe"
          if (Test-Path $tailscaleExe) {
              & $tailscaleExe up --authkey $env:TAILSCALE_AUTHKEY
          } else {
              Write-Error "Не найден tailscale.exe по пути: $tailscaleExe"
              exit 1
          }

      - name: Включаем RDP
        shell: powershell
        run: |
          Write-Output "Включаем удалённый рабочий стол (RDP)..."
          # Разрешаем подключения по RDP путём изменения системного реестра:
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          # Включаем правила брандмауэра для RDP:
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
