name: Temporary VPN with Amnesia VPN

on:
  push:
    branches:
      - main

jobs:
  vpn-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Install Amnesia VPN
      run: |
        git clone https://github.com/amnesia-vpn/amnesia.git
        cd amnesia
        sudo ./install.sh

    - name: Start Amnesia VPN
      run: |
        sudo systemctl start amnesia-vpn

    - name: Wait for VPN to establish
      run: sleep 30  # Даем время VPN для установления соединения

    - name: Your VPN-dependent task
      run: |
        curl ifconfig.me  # Проверим внешний IP, чтобы убедиться в подключении

    - name: Stop VPN container
      run: |
        sudo docker stop amnesia-vpn
