name: View Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Запуск каждые 10 минут
  workflow_dispatch:

jobs:
  view:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Send views
        run: |
          for i in {1..100}; do
            curl -s "https://rscripts.net/script/velocity-v2-98percent-unc-keyless-zMEq" > /dev/null
            echo "View $i sent"
            sleep 3
          done
