name: Run Xray (VLESS) in GitHub Actions

on:
  workflow_dispatch:  # Запуск вручную

jobs:
  run-xray:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Ограничение в 6 часов

    steps:
      - name: Установка Xray
        run: |
          sudo apt update
          sudo apt install -y curl unzip
          curl -Lo xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip xray.zip -d xray
          chmod +x xray/xray

      - name: Генерация UUID
        run: echo "UUID=$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_ENV

      - name: Создание конфигурации Xray
        run: |
          mkdir -p /etc/xray
          cat <<EOF > /etc/xray/config.json
          {
            "inbounds": [
              {
                "port": 443,
                "protocol": "vless",
                "settings": {
                  "clients": [
                    {
                      "id": "$UUID",
                      "flow": "xtls-rprx-vision"
                    }
                  ],
                  "decryption": "none"
                },
                "streamSettings": {
                  "network": "ws",
                  "wsSettings": {
                    "path": "/vless"
                  }
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {}
              }
            ]
          }
          EOF

      - name: Запуск Xray
        run: |
          nohup ./xray/xray -c /etc/xray/config.json > xray.log 2>&1 &

      - name: Вывод информации
        run: |
          echo "### VLESS Configuration" >> $GITHUB_STEP_SUMMARY
          echo "- **UUID:** $UUID" >> $GITHUB_STEP_SUMMARY
          echo "- **Server IP:** $(curl -s ifconfig.me)" >> $GITHUB_STEP_SUMMARY
          echo "- **Port:** 443" >> $GITHUB_STEP_SUMMARY
          echo "- **WebSocket Path:** /vless" >> $GITHUB_STEP_SUMMARY
