name: Run Xray (VLESS) in GitHub Actions with Tailscale

on:
  workflow_dispatch:  # Запуск вручную

jobs:
  run-xray:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Ограничение в 6 часов

    steps:
      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y curl unzip

      - name: Установка Xray
        run: |
          curl -Lo xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip xray.zip -d xray
          chmod +x xray/xray

      - name: Генерация UUID
        run: echo "UUID=$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_ENV

      - name: Установка Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=tskey-auth-kACuy7yZC711CNTRL-w6pX37eHwVUJBHTx1HYRWUrBtJ2D9E2rZ  # Токен для авторизации

      - name: Создание конфигурации Xray
        run: |
          cat <<EOF > config.json
          {
            "inbounds": [
              {
                "port": 8080,
                "protocol": "vless",
                "settings": {
                  "clients": [
                    {
                      "id": "$UUID",
                      "flow": "xtls-rprx-vision"
                    }
                  ],
                  "decryption": "none"
                },
                "streamSettings": {
                  "network": "ws",
                  "wsSettings": {
                    "path": "/vless"
                  }
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {}
              }
            ]
          }
          EOF

      - name: Запуск Xray и подключение через Tailscale
        run: |
          nohup ./xray/xray -c config.json > xray.log 2>&1 &
          sleep 5  # Даем Xray время запуститься

      - name: Получение Tailscale IP
        run: |
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: Вывод информации
        run: |
          echo "### VLESS Configuration" >> $GITHUB_STEP_SUMMARY
          echo "- **UUID:** $UUID" >> $GITHUB_STEP_SUMMARY
          echo "- **Tailscale IP:** $TAILSCALE_IP" >> $GITHUB_STEP_SUMMARY
          echo "- **Port:** 8080" >> $GITHUB_STEP_SUMMARY
          echo "- **WebSocket Path:** /vless" >> $GITHUB_STEP_SUMMARY

      - name: Удержание процесса активным
        run: tail -f /dev/null
