name: Tailscale Exit Node
on: workflow_dispatch  # <--- REMOVE EXTRA SPACES BEFORE "on"
jobs:
  setup-exit-node:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and Advertise Exit Node
        env:
          AUTH_KEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscale up --authkey=$AUTH_KEY \
                            --hostname=github-actions-exit-node \
                            --advertise-exit-node \
                            --exit-node=fra  # <-- Укажите ближайший DERP-регион
          sleep 300  # Keep alive for 5 minutes
