name: Outline VPN Server

on:
  workflow_dispatch:

jobs:
  start-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Установить зависимости
        run: |
          sudo apt update
          sudo apt install -y docker.io curl jq

      - name: Запустить Outline VPN сервер
        run: |
          docker run -d --name outline-server -p 8388:8388 \
          -e ACCESS_KEY="123" \
          ghcr.io/jorgeandrada/outline-ss-server:latest

      - name: Вывести IP-адрес runner'а
        run: curl ifconfig.me
