name: Deploy VLESS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Xray
        run: |
          sudo curl -O https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh
          sudo bash install-release.sh

      - name: Configure VLESS
        run: |
          sudo mkdir -p /etc/xray
          sudo tee /etc/xray/config.json > /dev/null <<EOF
          {
            "inbounds": [{
              "port": 443,
              "protocol": "vless",
              "settings": {
                "clients": [{
                  "id": "12345678-90ab-cdef-1234-567890abcdef",
                  "flow": "xtls-rprx-vision"
                }],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                  "certificates": [{
                    "certificateFile": "/etc/xray/fullchain.pem",
                    "keyFile": "/etc/xray/privkey.pem"
                  }]
                }
              }
            }],
            "outbounds": [{
              "protocol": "freedom"
            }]
          }
          EOF
          sudo systemctl enable xray
          sudo systemctl restart xray

      - name: Show VLESS Link
        run: |
          SERVER_IP=$(curl -s ifconfig.me)
          echo "VLESS Link:"
          echo "vless://12345678-90ab-cdef-1234-567890abcdef@$SERVER_IP:443?security=tls&type=ws"
