name: Temporary VPN

on:
  push:
    branches:
      - main

jobs:
  vpn:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Remove conflicting containerd package
        run: |
          sudo apt-get remove -y containerd
          sudo apt-get autoremove -y

      - name: Clean apt cache and update
        run: |
          sudo apt-get clean
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io

      - name: Run Amnesia VPN container
        run: |
          sudo docker run --rm -d \
            --name amnesia-vpn \
            --cap-add=NET_ADMIN \
            --device /dev/net/tun \
            amnesia/amnesia-vpn

      - name: Wait for VPN to establish
        run: sleep 30

      - name: Your VPN-dependent task
        run: |
          curl ifconfig.me

      - name: Stop VPN container
        run: |
          sudo docker stop amnesia-vpn
