name: Temporary VPN with Amnesia VPN

on:
  push:
    branches:
      - main

jobs:
  vpn-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Install Amnesia VPN
      run: |
        git clone https://github.com/amnesia-vpn/amnesia.git
        cd amnesia
        sudo ./install.sh

    - name: Start Amnesia VPN
      run: |
        sudo systemctl start amnesia-vpn

    - name: Wait for VPN to establish
      run: sleep 30

    - name: Verify VPN connection
      run: |
        curl ifconfig.me  # Check the external IP to verify VPN connection

    - name: Your VPN-dependent task
      run: |
        curl ifconfig.me  # Verify VPN is working

    - name: Stop VPN container
      run: |
        sudo systemctl stop amnesia-vpn      - name: Your VPN-dependent task
        run: |
          curl ifconfig.me

      - name: Stop VPN container
        run: |
          sudo docker stop amnesia-vpn
