name: Deploy VLESS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Xray
        run: |
          sudo curl -O https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh
          sudo bash install-release.sh

      - name: Configure VLESS
        run: |
          sudo mkdir -p /etc/xray
          sudo tee /etc/xray/config.json > /dev/null <<EOF
          {
            "inbounds": [{
              "port": 443,
              "protocol": "vless",
              "settings": {
                "clients": [{
                  "id": "12345678-90ab-cdef-1234-567890abcdef",
                  "flow": "xtls-rprx-vision"
                }],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                  "certificates": [{
                    "certificateFile": "/etc/xray/fullchain.pem",
                    "keyFile": "/etc/xray/privkey.pem"
                  }]
                }
              }
            }],
            "outbounds": [{
              "protocol": "freedom"
            }]
          }
          EOF
          sudo systemctl restart xray

      - name: Show VLESS Link
        run: |
          echo "VLESS Link:"
          echo "vless://12345678-90ab-cdef-1234-567890abcdef@your-server-ip:443?security=tls&type=ws"                    "certificateFile": "/etc/xray/fullchain.pem",
                    "keyFile": "/etc/xray/privkey.pem"
                  }]
                }
              }
            }],
            "outbounds": [{
              "protocol": "freedom"
            }]
          }
          EOF
          systemctl restart xray

      - name: Show VLESS Link
        run: |
          echo "VLESS Link:"
          echo "vless://12345678-90ab-cdef-1234-567890abcdef@your-server-ip:443?security=tls&type=ws"              Write-Error "Не найден tailscale.exe по пути: $tailscaleExe"
              exit 1
          }

      - name: Включаем RDP
        shell: powershell
        run: |
          Write-Output "Включаем удалённый рабочий стол (RDP)..."
          # Разрешаем подключения по RDP путём изменения системного реестра:
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          # Включаем правила брандмауэра для RDP:
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
