name: Outline VPN on GitHub Actions

on:
  workflow_dispatch:

jobs:
  outline:
    runs-on: ubuntu-latest
    steps:
      - name: Удаление возможных конфликтующих пакетов
        run: |
          sudo apt-get remove -y containerd.io || true
          sudo apt-get autoremove -y
          sudo apt-get update

      - name: Установка Docker без containerd.io
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd

      - name: Запуск Outline VPN
        run: |
          docker run -d --name outline-server \
            -p 1024-65535:1024-65535/udp \
            -p 1024-65535:1024-65535/tcp \
            quay.io/outline/shadowbox:stable

      - name: Проверка логов
        run: docker logs outline-server
