name: Deploy VLESS VPN on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Настройка SSH для подключения к серверу
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг 3: Установка зависимостей на сервере
      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
            sudo apt update
            sudo apt install -y wget unzip
            sudo apt install -y curl
            sudo apt install -y ufw
            sudo ufw allow 443/tcp
            sudo ufw enable
          EOF

      # Шаг 4: Установка Xray (или V2Ray)
      - name: Install Xray (VLESS)
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
            wget https://github.com/XTLS/Xray-core/releases/download/v1.8.0/Xray-linux-amd64-v1.8.0.tar.gz
            tar -xvzf Xray-linux-amd64-v1.8.0.tar.gz
            sudo mv xray /usr/local/bin/xray
            sudo chmod +x /usr/local/bin/xray
          EOF

      # Шаг 5: Конфигурация Xray
      - name: Configure Xray
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
            mkdir -p /etc/xray
            echo '{
              "inbounds": [
                {
                  "port": 443,
                  "listen": "0.0.0.0",
                  "protocol": "vless",
                  "settings": {
                    "clients": [
                      {
                        "id": "your-uuid", 
                        "alterId": 64
                      }
                    ]
                  },
                  "streamSettings": {
                    "network": "tcp",
                    "security": "tls",
                    "tlsSettings": {
                      "certificates": [
                        {
                          "certificateFile": "/etc/ssl/certs/your-certificate.crt",
                          "keyFile": "/etc/ssl/private/your-private.key"
                        }
                      ]
                    }
                  }
                }
              ],
              "outbounds": [
                {
                  "protocol": "freedom"
                }
              ]
            }' | sudo tee /etc/xray/config.json
          EOF

      # Шаг 6: Запуск Xray
      - name: Start Xray
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
            sudo systemctl enable xray
            sudo systemctl start xray
          EOF

      # Шаг 7: Проверка статуса Xray
      - name: Check Xray status
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
            sudo systemctl status xray
          EOF
