- name: Start Tailscale and Advertise Exit Node
        env:
          AUTH_KEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscale up --authkey=$AUTH_KEY \
                            --hostname=github-actions-exit-node \
                            --advertise-exit-node \
                            --exit-node-allow-lan-access \
                            --accept-routes
          
          # Указываем предпочтительный DERP-сервер (например, Германия)
          sudo tailscale set --prefs='{"WantDERP": 1, "DERPMap": {"Regions": {"999": {"RegionCode": "DE"}}}}'
          
          sleep 300  # Keep alive for 5 minutes
