name: Setup Outline VPN

on:
  push:
    branches:
      - main

jobs:
  outline-vpn-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Outline VPN Docker image
        run: docker pull outline/outline-server:latest

      - name: Run Outline VPN container
        run: |
          docker run -d --name outline-vpn -p 80:80 outline/outline-server
          
      - name: Get server public IP
        run: curl ifconfig.me

      - name: Output VPN details
        run: |
          echo "Outline VPN Server running at: $(curl -s ifconfig.me)"
